# Prosty pipeline build (np. Google Cloud Build / inny runner z dockerem)
steps:
  - name: node:20
    entrypoint: bash
    args:
      - "-c"
      - |
        npm ci
        npm run build

artifacts:
  objects:
    location: dist/
    paths:
      - "**"
